### ISSUE TITLE
在PC端页面显示效果不好

### ISSUE THREAD

**Issue by shuen2023** [zyronon/typing-word#1]
我在电脑上使用chrome打开界面就好像没有优化好的手机端页面一样请再改进下吧。很喜欢在右侧显示的单词列表。可我设置了单词重复好像不起作用。英式发音设置了好像也不起作用。

**Comment by zyronon** [comment]
好的，谢谢支持，正在开发中，还没弄完呢😂，单词重复和英式发音还没来得及加上

**Comment by shuen2023** [comment]
> 好的，谢谢支持，正在开发中，还没搞完呢😂，单词重复和英式发音还没来得及加上

大佬你总算回复我了，我可喜欢你的这个项目了。

**Comment by zyronon** [comment]
😊开发好了叫你（加班加点开发中...

**Comment by shuen2023** [comment]
> 😊开发好了叫你（加班加点开发中...

谢谢 😄

**Comment by zyronon** [comment]
英式发音和单词重复这个修复了。其他功能任在开发中...

**Comment by zyronon** [comment]
你是说页面卡吗？你是本地启动的还是打开的这个https://typing-words.netlify.app/ 地址来使用的？

**Comment by shuen2023** [comment]
> 你是说页面卡吗？你是本地启动的还是打开这个https://typing-words.netlify.app/地址来使用的？      

我就是点击链接使用的。当时在pc端觉得这个页面和手机端区别不大设计好像更符合在手机端使用。但我刚才又打开链接看了下也挺好的了。

**Comment by shuen2023** [comment]
> 英式发音和单词重复这个修复了。其他功能任在开发中...

谢谢😊

**Comment by shuen2023** [comment]
大佬辛苦了！这个网址是不是只能挂VPN访问。我断掉VPN就不能访问了。  
另外英音发音当前的单词没有音标显示了，只能看右侧列表。  
单词循环次数自定义还不能用对吧。  
大佬这个项目很棒，很喜欢。你有时间给弄就行。谢谢😊

**Comment by shuen2023** [comment]
我想尽可能表达清楚一点关于pc端页面显示不大好的地方在于，如果不放大页面它看上去有些小，当我手动放大页面有些按钮选项看上去就挤压变形了。  尤其会影响到右侧列表(我非常喜欢右侧列表的这个设计)。可是页面左侧却有一大部分空间。

**Comment by shuen2023** [comment]
> 英式发音和单词重复这个修复了。其他功能任在开发中...

刚发现。单词循环可能存在失效。我刚才打到两个词set和key，我设置好了循环五次。我上来输错了几次后，即使我输入正确了，但是它会一直循环下去。这个对于只有几个字母字母不多的单词更能显现出来。我只能按tab切换，这个tab你可以考虑换成回车键嘛。回车键也好按。

**Comment by zyronon** [comment]
一、关于快捷键，我会弄一个可自定义的，毕竟每个人的习惯不同，一开始就规划好的，只是还没来得及做

二、关于访问

   1. https://typing-words.netlify.app  用netlify部署的，需要VPN

   2. https://zyronon.github.io/typing-word/  用Github Pages部署的，不需要VPN但打开速度慢
   
   3. 本想用Gitee Pages部署的，尽然要提交手持身份证审核，要1-2天。下周我会尽快部署到Gitee Pages，那样就不需要VPN且打开速度快了

三、关于UI：
  1. 目前做的布局和样式均是针对电脑网页的，手机上没有专门适配。后续会专门适配手机和平板
  2. 英音发音当前的单词没有音标，是词典的问题，词典就没有英音音标，词典我也是拿的别人的....后续考虑整一本大而全的词典或者在线查询翻译、音标。右侧列表目前显示的一直是美音音标（是个Bug）....😂

四、单词循环、自定义循环，我这边试了没问题啊。逻辑是， “把单词正确打完整   x   循环次数”，比如说你第一遍，不管你错了几次，直到你把单词正确打完，“这个单词的 循环次数” 才会加1，同理，第二遍时，你又错了，但是只有你把单词正确打完，“这个单词的 循环次数” 才会加1，直到 “这个单词的 循环次数” 等于 设定的 “循环次数”才会进入下一个词

五、页面看上去小....麻将提供下你的屏幕分辨率和缩放比🤣，我是24寸开发的....

**Comment by shuen2023** [comment]
> 一、关于快捷键，我会弄一个可自定义的，毕竟每个人的习惯不同，一开始就规划好的，只是还没来得及做
> 
> 二、关于访问
> 
> 1. https://typing-words.netlify.app  用netlify部署的，需要VPN
> 2. https://zyronon.github.io/typing-word/  用Github Pages部署的，不需要VPN但打开速度慢
> 3. 本想用Gitee Pages部署的，尽然要提交手持身份证审核，要1-2天。下周我会尽快部署到Gitee Pages，那样就不需要VPN且打开速度快了
> 
> 三、关于UI：
> 
> 1. 目前做的布局和样式均是针对电脑网页的，手机上没有专门适配。后续会专门适配手机和平板
> 2. 英音发音当前的单词没有音标，是词典的问题，词典就没有英音音标，词典我也是拿的别人的....后续考虑整一本大而全的词典或者在线查询翻译、音标。右侧列表目前显示的一直是美音音标（是个Bug）....😂
> 
> 四、单词循环、自定义循环，我这边试了没问题啊。逻辑是， “把单词正确打完整 x 循环次数”，比如说你第一遍，不管你错了几次，直到你把单词正确打完，“这个单词的 循环次数” 才会加1，同理，第二遍时，你又错了，但是只有你把单词正确打完，“这个单词的 循环次数” 才会加1，直到 “这个单词的 循环次数” 等于 设定的 “循环次数”才会进入下一个词
> 
> 五、页面看上去小....麻将提供下你的屏幕分辨率和缩放比🤣，我是24寸开发的....

额，谢谢，我的是笔记本16寸的好像，分辨率是1920*1080我使用chrome要放大到百分之二百我觉得才算合适。

**Comment by shuen2023** [comment]
我再次确认了关于设置循环次数失效的问题。我是选择了计算机专用英语，单词循环次数五次。但当我打到line词时问题重现。设置的循环次数失效了它似乎无限重复。只能使用按键跳过。

**Comment by shuen2023** [comment]
我录了个屏，包括自定义循环不能用。

https://github.com/zyronon/typing-word/assets/133501179/ff8df7b6-cdc4-4ca3-9110-28de19199154

**Comment by zyronon** [comment]
好的，收到，我马上看看

**Comment by zyronon** [comment]
我知道原因了，你先别输入那么快。我只判断了  === 。你输入太快了，导致 本地循环的次数 大于 了设定的循环次数了 ，所以一直循环，是个bug，我晚点修复

**Comment by shuen2023** [comment]
> 我知道原因了，你先别输入那么快。我只判断了 === 。你输入太快了，导致 本地循环的次数 大于 了设定的循环次数了 ，所以一直循环，是个bug，我晚点修复

噢，谢谢😊

**Comment by zyronon** [comment]
已修复

**Comment by shuen2023** [comment]
> 已修复

谢谢😊

**Comment by zyronon** [comment]
> > 英式发音和单词重复这个修复了。其他功能任在开发中...
> 
> 刚发现。单词循环可能存在失效。我刚才打到两个词set和key，我设置好了循环五次。我上来输错了几次后，即使我输入正确了，但是它会一直循环下去。这个对于只有几个字母字母不多的单词更能显现出来。我只能按tab切换，这个tab你可以考虑换成回车键嘛。回车键也好按。

自定义快捷键 做好了

![image](https://github.com/zyronon/typing-word/assets/19986642/6d1e4e9a-ee43-49ec-8bac-774abd3e1518)

**Comment by shuen2023** [comment]
> > > 英式发音和单词重复这个修复了。其他功能任在开发中...
> > 
> > 
> > 刚发现。单词循环可能存在失效。我刚才打到两个词set和key，我设置好了循环五次。我上来输错了几次后，即使我输入正确了，但是它会一直循环下去。这个对于只有几个字母字母不多的单词更能显现出来。我只能按tab切换，这个tab你可以考虑换成回车键嘛。回车键也好按。
> 
> 自定义快捷键 做好了
> 
> ![image](https://user-images.githubusercontent.com/19986642/280764933-6d1e4e9a-ee43-49ec-8bac-774abd3e1518.png)

谢谢😊
