### ISSUE TITLE
日语支持在哪？

### ISSUE THREAD

**Issue by noexpect9** [zyronon/typing-word#13]
大佬，词库支持上有日语 在哪找？单词列表没有找到

**Comment by zyronon** [comment]
有的，但是目前有些问题，正在改

**Comment by noexpect9** [comment]
可以提PR吗？ 目前待开发的功能有改变吗？
![image](https://github.com/zyronon/typing-word/assets/97077898/ceed790f-dffb-498b-9b23-b5ffe6ebcdd5)

**Comment by zyronon** [comment]
可以提pr，dev是最新代码，目前在开发手机端

**Comment by zyronon** [comment]
日语的字典需要写个脚本全部跑一遍才能用

**Comment by noexpect9** [comment]
日语需要如何处理？我看词库有的 没发音

**Comment by zyronon** [comment]
> 日语需要如何处理？我看词库有的 没发音

在dev分支，我放开了日语的限制，可以在弹框里面选到。发音目前不能自动切换，所以我写死了。不过不能打字输入日语，目前只支持英文输入

改那个还挺麻烦的，我后面有空改

你可以直接用这个网站：https://qwerty.kaiyi.cool/，他目前是支持日语的。我本身也从这个网站看到的创意。

**Comment by zyronon** [comment]
如果你想提pr的话，可以加我微信zyrican
