### ISSUE TITLE
Macos 部署遇到vue/macros问题

### ISSUE THREAD

**Issue by lekuejj** [zyronon/typing-word#14]
按照大神的步骤部署后，发现一大堆报错，主要为：
 [ERROR] Missing "./macros" specifier in "vue" package [plugin vite:dep-scan]
网上找了几天，发现为 https://github.com/vitejs/vite/issues/15484 这里描述的问题。

解决方案为：  "vue": "^3.3.4", 降级到"vue": "~3.3.13"，希望能帮到需要的人。

**Comment by horennel** [comment]
谢谢大佬，前端小白表示早点看到你的Issues就不用折腾半天了

**Comment by zyronon** [comment]
谢谢大佬，我把依赖锁版本了

**Comment by XmJwit** [comment]
另外一种方案是安装独立版本 Reactivity Transform
```
npm i -D @vue-macros/reactivity-transform
```

ref:
https://cn.vuejs.org/guide/extras/reactivity-transform#explicit-opt-in
https://vue-macros.dev/zh-CN/features/reactivity-transform.html
