### ISSUE TITLE
使用docker部署该项目

### ISSUE THREAD

**Issue by horennel** [zyronon/typing-word#15]
项目根目录创建Dockerfile文件
FROM node
COPY . /root/typing-word
WORKDIR /root/typing-word
EXPOSE 3000
RUN npm install && npm uninstall vue && npm install vue@3.3.13
CMD ["npm", "start"]

创建镜像 `docker build -t typing-word:001 .`

启动容器 `docker run --name typing-word -p 3000:3000 -d typing-word:001`

**Comment by zyronon** [comment]
谢谢大佬，照着你的添加了

**Comment by Crescentz** [comment]
有现成的docker文件吗
