### ISSUE TITLE
章节的第一个单词有时可能会出现没有反应的情况

### ISSUE THREAD

**Issue by shuen2023** [zyronon/typing-word#2]
当我完成一小章节后，正常情况会进入下一章节，并从第一个单词重新开始。可有时候要先点击右侧列表的第二个单词(除了第一个点了没反应其它估计都可以)，然后再回到第一个才会自动开始。   
这种情况不确定在切换单词章节时会不会出现。但完成某章节我已经碰到几次了。  

https://github.com/zyronon/typing-word/assets/133501179/ecf0a4f2-08bf-4a2a-964e-c5a65829133d

**Comment by shuen2023** [comment]
这个链接的[https://typing-words.netlify.app/]

**Comment by zyronon** [comment]
好的，收到

**Comment by zyronon** [comment]
你经常用哪本词典啊

**Comment by shuen2023** [comment]
> 你经常用哪本词典啊

计算机专业英语。

**Comment by zyronon** [comment]
应该是快速切换，导致单词没发音的bug。已经修复了

**Comment by shuen2023** [comment]
> 应该是快速切换，导致单词没发音的bug。已经修复了

谢谢😊
