### ISSUE TITLE
功能请求 | 请求只显示英文，不显示中文的功能

### ISSUE THREAD

**Issue by langyxxl** [zyronon/typing-word#21]
1、描述
只显示英文，不显示中文的功能，可以快速确认单词是否认识
  
2、这个功能解决了什么问题？
解决了快速确认单词是否认识

**Comment by zyronon** [comment]
顶部有图标可以关啊

或者按ctrl + z也行

**Comment by langyxxl** [comment]
感谢，试了一下，确实可以了，但是收藏和错词本里面还是会有中文显示，这个里面的中文也能一起关闭么

还有就是发现ctrl z关闭开始过程中，列表里面每个单词的排列长度会发生改变，导致ui变化，不太完美

**Comment by zyronon** [comment]
这个是没有办法的
