### ISSUE TITLE
问题报告 | Bug report IMPORTANT!!!!

### ISSUE THREAD

**Issue by brizer** [zyronon/typing-word#22]
### 注意：请确认问题可以在浏览器的  无痕模式  下复现，而不是自己安装的其他插件或脚本导致的

1、描述
在这里填写问题描述

2、截图
可以直接按Ctrl + V 复制在这里（复制成功后会显示一串地址）

### Note: Please confirm that the problem can be reproduced in the browser's traceless mode, rather than being caused by other plugins or scripts installed by yourself

1. Description
Fill in the problem description here

2. Screenshot
You can directly press Ctrl+V to copy here (a string of addresses will be displayed after successful copying)

 你好，我是抖音、哔哩哔哩、头条、微信视频号技术工具up主，看到你的产品很好，想帮推，需要的话加微信：brizer1992

**Comment by zyronon** [comment]
好的
