### ISSUE TITLE
请求改进界面布局

### ISSUE THREAD

**Issue by shuen2023** [zyronon/typing-word#3]
界面布局有些太靠右侧了,尤其在放大时。

**Comment by zyronon** [comment]
好的

**Comment by zyronon** [comment]
不太明白你的意思呢，你说的是单词列表吗

**Comment by shuen2023** [comment]
> 不太明白你的意思呢，你说的是单词列表吗

对，你看左面那么多地方还没用

**Comment by zyronon** [comment]
你屏幕分辨率是多少啊

**Comment by shuen2023** [comment]
> 你屏幕分辨率是多少啊

1920*1080😊

**Comment by zyronon** [comment]
不，我要看你缩放之后的分辨率

1、
![image](https://github.com/zyronon/typing-word/assets/19986642/0421848f-53bb-45b4-96cb-b83869e20f2a)

2、
![image](https://github.com/zyronon/typing-word/assets/19986642/a32e8497-c1bd-47ee-bf83-46b313711c67)

**Comment by shuen2023** [comment]
> 不，我要看你缩放之后的分辨率
> 
> 1、 ![image](https://user-images.githubusercontent.com/19986642/279272678-0421848f-53bb-45b4-96cb-b83869e20f2a.png)
> 
> 2、 ![image](https://user-images.githubusercontent.com/19986642/279272776-a32e8497-c1bd-47ee-bf83-46b313711c67.png)

好，谢谢，我晚点回家再回你。不是放大后的对吧

**Comment by shuen2023** [comment]
> 不，我要看你缩放之后的分辨率
> 
> 1、 ![image](https://user-images.githubusercontent.com/19986642/279272678-0421848f-53bb-45b4-96cb-b83869e20f2a.png)
> 
> 2、 ![image](https://user-images.githubusercontent.com/19986642/279272776-a32e8497-c1bd-47ee-bf83-46b313711c67.png)

80%缩放后的分辨率是1920*932。  
![截图](https://github.com/zyronon/typing-word/assets/133501179/4118dec8-925c-4480-8b99-1068ff2707bb)
我觉得这才可能是正常的界面，因为如果我放大后自定义循环单词设置那个地方输入的内容看不到。这个80%缩放后能看到输入三位数。

**Comment by shuen2023** [comment]
而且，这么缩放后除了字太小外。实际上界面各部分比例挺正常了。因为主要放大后使用，看上去界面布局比例分布总觉得不恰当。
