### ISSUE TITLE
英语单词字体设置100后音标与收藏跳转ico图标重叠

### ISSUE THREAD

**Issue by shuen2023** [zyronon/typing-word#6]
我在之前开过一个美化界面的问题但都没能很好的说明情况。我当时想如果它能自适应当前界面那就好了，放大它们会相应的都协调放大。但似乎不太可能。  
![Clip_20231108_164221](https://github.com/zyronon/typing-word/assets/133501179/299ecd30-2bfd-48aa-8b79-dce538b7ee93)        

1. 当我把英语字体设置成100后。它跟对应的汉字上下间距是不是有点小，接近重叠。但我设置大了英语那么就想去设置汉字可它俩的间距好像是个问题。。  
2. 音标大小好像不能设置没找到在哪儿设置。当单词和汉字设置完后音标显得有点太小。
3. 音标下方的收藏跳转那三个ico和音标的直接重叠了。那三个ico,收藏,跳转的是否可以再往下面移一些。 或者直接移到顶部那一工具栏。  
4. 快捷键有跳转设置，能不能再给个返回上一个单词的快捷键。有时候想返回只能鼠标点，但如果不离开键盘那会更享受。

**Comment by zyronon** [comment]
好

**Comment by zyronon** [comment]
没想到你竟然弄这么大来使用...

**Comment by shuen2023** [comment]
> 没想到你竟然弄这么大来使用...

😁俺用的笔记本，屏幕太小。以前没太注意可以设置字体大小☺️

**Comment by zyronon** [comment]
试一试呢，我针对低分辨率调整了布局

![image](https://github.com/zyronon/typing-word/assets/19986642/eab14464-530a-4eab-b0e6-8f2929a7f90d)

快捷键：加了“上一个”，默认为Alt+⬅，不喜欢可以自己调一下。另外“下一个”的快捷键被重置了，如果你要自定义的话，需要重新设置一下哦

其他的几个问题，后面再修复，好了通知你

**Comment by shuen2023** [comment]
> 试一试呢，我针对低分辨率调整了布局
> 
> ![image](https://user-images.githubusercontent.com/19986642/281461250-eab14464-530a-4eab-b0e6-8f2929a7f90d.png)
> 
> 快捷键：加了“上一个”，默认为Alt+⬅，不喜欢可以自己调一下。另外“下一个”的快捷键被重置了，如果你要自定义的话，需要重新设置一下哦
> 
> 其他的几个问题，后面再修复，好了通知你


非常感谢😊!  
就是能不能再把那个单词列表③那一框往右移一点，(只移动单词本列表框)其它不动。移大概两个间距(截图标的①和②之间的缝隙)的长度。不然它太靠近我打的单词那感觉就好像在比着书本抄书一样，因为有时我还想看到这个单词列表。     
太感谢你了!

![IMG_20231109_002239_edit_43269692416565](https://github.com/zyronon/typing-word/assets/133501179/dd5ef73e-06b9-4f7d-a5f1-848b1f807147)

**Comment by shuen2023** [comment]
我突然觉得大佬可以考虑后面做成，自定义布局的。免得各自的需求可能会不一样。就是界面看到的都可以随手拖拽，并且可以固定。像列表框就是一个单独的我自己可以到处拖放。单词也和中文释义也是各自为一个可选区。等等

**Comment by zyronon** [comment]
自定义布局后期可以考虑，那玩意挺麻烦的。我准备加个快捷键以隐藏/显示单词列表

明天有空了改下你说的那个间隙

还有许多基础功能没做呢，欸。现在只做保存设置，还不能保存背诵记录，每次打开都得重选

**Comment by shuen2023** [comment]
> 自定义布局后期可以考虑，那玩意挺麻烦的。我准备加个快捷键以隐藏/显示单词列表
> 
> 明天有空了改下你说的那个间隙
> 
> 还有许多基础功能没做呢，欸。现在只做保存设置，还不能保存背诵记录，每次打开都得重选

😀谢谢，不着急，你抽空给弄就行。先把基础的弄好。你做的这个项目很棒很棒了。我觉得了不起。谢谢你。

**Comment by shuen2023** [comment]
开发不易。就我了解到的所有类似的开源项目里面你的这个算是比较专业的了。希望能能够完善坚持下去。去宣传下，打赏码贴出来。我也在b站简单的发过视频。但当时只是觉得非常好，并没有详细的介绍到重点。

**Comment by zyronon** [comment]
> 开发不易。就我了解到的所有类似的开源项目里面你的这个算是比较专业的了。希望能能够完善坚持下去。去宣传下，打赏码贴出来。我也在b站简单的发过视频。但当时只是觉得非常好，并没有详细的介绍到重点。

谢谢，我这个项目是仿的 https://github.com/RealKai42/qwerty-learner 这个项目，我想等做到完美了再去推广，不想做个半成品就让人来用，那样没意义，也骗不到star了😂。因为有了同样类型的项目，我必须做的更好才有人用。


我还纳闷为啥突然多了几个star，原来是你帮我宣传了，非常感谢。

**Comment by zyronon** [comment]
另外，这个项目，其实我还打算打文章练习的，也算是一个主打功能，但是还没做完

**Comment by zyronon** [comment]
后续如果有人用的话，还考虑适配平板，通过手写来记单词

**Comment by shuen2023** [comment]
> > 开发不易。就我了解到的所有类似的开源项目里面你的这个算是比较专业的了。希望能能够完善坚持下去。去宣传下，打赏码贴出来。我也在b站简单的发过视频。但当时只是觉得非常好，并没有详细的介绍到重点。
> 
> 谢谢，我这个项目是仿的 https://github.com/RealKai42/qwerty-learner 这个项目，我想等做到完美了再去推广，不想做个半成品就让人来用，那样没意义，也骗不到star了😂。因为有了同样类型的项目，我必须做的更好才有人用。
> 
> 我还纳闷为啥突然多了几个star，原来是你帮我宣传了，非常感谢。

😊第一次搜到就没忍住去B站发了个视频。  
你以后可别搞成收费才能使用的啊。

**Comment by shuen2023** [comment]
> 后续如果有人用的话，还考虑适配平板，通过手写来记单词

我昨天手机端打开看了下，是不好。我想如果用平板打开，无限键盘打字也挺好的。

**Comment by shuen2023** [comment]
> 另外，这个项目，其实我还打算打文章练习的，也算是一个主打功能，但是还没做完

我反正被那个错词本之类的惊艳到了☺️

**Comment by zyronon** [comment]
不会收费，代码都是开源的。自己下载下来也可以用的。俺不为钱就想弄点star。因为简历上没亮点😂😂

你看  https://github.com/RealKai42/qwerty-learner  这个项目都有12.9k的star，你就知道多么离谱了

**Comment by zyronon** [comment]
> > 后续如果有人用的话，还考虑适配平板，通过手写来记单词
> 
> 我昨天手机端打开看了下，是不好。我想如果用平板打开，无限键盘打字也挺好的。

压根就没适配平板和手机屏幕，还没考虑好怎么使用。主要是手机上有许多专业的app，也没啥必要用我这个网页了感觉

**Comment by shuen2023** [comment]
> > > 后续如果有人用的话，还考虑适配平板，通过手写来记单词
> > 
> > 
> > 我昨天手机端打开看了下，是不好。我想如果用平板打开，无限键盘打字也挺好的。
> 
> 压根就没适配平板和手机屏幕，还没考虑好怎么使用。主要是手机上有许多专业的app，也没啥必要用我这个网页了感觉

嗯。
