### ISSUE TITLE
项目进展

### ISSUE THREAD

**Issue by zyronon** [zyronon/typing-word#7]
目前项目的基础体验已经相对完善，可以很好的满足大部分用户背单词的需求。

# 目前正在开发功能
- [x] 实现单词发音速度调节
- [x] 音量大小调节
- [x] 自行收藏单词、自行添加词典
- [x] 单个章节可以打乱顺序
- [x] 自定义每个章节的数量
- [x] 数据导入导出
- [ ] 适配手机端
- [ ] 账号系统，账号系统考虑接入第三方onedrive或者github、google等来同步数据
- [ ] 目前默认导出为excel格式，添加更多其他格式
- [ ] 词典管理是在另一个页面，考虑将操作进一步简化和添加教学引导
- [ ] 例句
- [x] 背单词时增加选择，可选不自动跳转到下一个，而是按一下空格
- [ ] 朗读一下释义/翻译发音

**Comment by tiwentichat** [comment]
大佬，在手机上没法使用啊
接下来会考虑这方面的适配不？
不单单是UI，手机上打开没有地方输入字母  - -！
还挺想用碎片时间刷一刷单词的 - -！

**Comment by zyronon** [comment]
> 大佬，在手机上没法使用啊 接下来会考虑这方面的适配不？ 不单单是UI，手机上打开没有地方输入字母 - -！ 还挺想用碎片时间刷一刷单词的 - -！

手机可以先使用单词app顶着呗。手机版说不定，未来看使用的人多不多，多就适配手机版😁

**Comment by tiwentichat** [comment]
> > 大佬，在手机上没法使用啊 接下来会考虑这方面的适配不？ 不单单是UI，手机上打开没有地方输入字母 - -！ 还挺想用碎片时间刷一刷单词的 - -！
> 
> 手机可以先使用单词app顶着呗。手机版说不定，未来看使用的人多不多，多就适配手机版😁

✓ 谢谢大佬回复！这个版本用着挺爽的，已经给不想用那些 APP了  哈哈哈

**Comment by vmvwv** [comment]
您好，能直接官方打包制作docker镜像，上传docker Hub吗？
这样大家使用会舒服很多，更新也方便。

**Comment by zhangjiuliang** [comment]
大佬我小丑了，我最近也在做这个web的都快做好了，但是不如你的

**Comment by zhangjiuliang** [comment]
你的这个功能太丰富了

**Comment by zhangjiuliang** [comment]
建议佬考虑一下快应用

**Comment by zhangjiuliang** [comment]
佬可以先做账号再做手机，这样直接多端同步了

**Comment by zyronon** [comment]
> 你的这个功能太丰富了

谬赞了

**Comment by zyronon** [comment]
> 佬可以先做账号再做手机，这样直接多端同步了

账号还没想好怎么做

**Comment by zhangjiuliang** [comment]
大二的时候写过app，太烂了不好意思拿出来

**Comment by zhangjiuliang** [comment]
自己用

**Comment by zhangjiuliang** [comment]
佬我想要错题本导出到excel或者yuque

**Comment by yanedie** [comment]
大佬真的是厂里自学的吗？居然不是科班专业人士

**Comment by zyronon** [comment]
> 大佬真的是厂里自学的吗？居然不是科班专业人士

真的

**Comment by surfingtomchen** [comment]
请问一下字典如何增加，我看了dict目录下的json中只有单词，没有翻译和音标，但是在translate下面有所有单词的读音和翻译，也就是新增字典的同时也需要增加翻译到这个文件下吗？这里是进行了合并操作吗？一个单词如果出现在不同的字典中，就是采用了统一的翻译？这个貌似对增加字典不是很友好，不能只导入一个文件

**Comment by GreyRaphael** [comment]
太棒了，配享太庙
